#!/usr/bin/python3

from optparse import OptionParser
from actions import reports

usage = "usage: %command [options] arg"
parser = OptionParser(usage)
parser.add_option("-f", "--file", dest="filename", help="read data from FILENAME")
parser.add_option("-v", "--verbose", action="store_true", dest="verbose")
parser.add_option("-q", "--quiet", action="store_false", dest="verbose")

(options, args) = parser.parse_args()

if len(args) < 1:
    parser.error("Please specify a command")

valid = False
if args[0] == 'gen':
    valid = reports.handle_gen(parser, options, args)
elif args[0] == 'process':
    valid = reports.handle_process(parser, options, args)

if not valid:
    parser.error('''Invalid args, review the info
''')