#!/usr/bin/python3

from optparse import OptionParser

from nitwit.actions import tags, categories, tickets, bulk, lists, init, usage
from nitwit.helpers.settings import load_settings

import sys, os


# Load the git/config settings file
if (settings := load_settings()) is None:
    print("Please only run inside of a git repo")
    exit(1)

if len(sys.argv) < 2:
    usage.show_usage()
    exit(1)

err = None

## Installation / Setup
if sys.argv[1] == 'init':
    err = init.handle_init( settings )

## Tickets
elif sys.argv[1] in ('ticket', 'tickets'):
    err = tickets.handle_ticket( settings )

## Tags
elif sys.argv[1] in ('tag', 'tags'):
    err = tags.handle_tag(settings)

## Categories
elif sys.argv[1] in ('category', 'categories'):
    err = categories.handle_category(settings)

## Lists
elif sys.argv[1] in ('list', 'lists'):
    err = lists.handle_list( settings )

## Bulk
elif sys.argv[1] == 'bulk':
    err = bulk.handle_bulk(settings)

elif sys.argv[1] == 'help':
    usage.show_usage( sys.argv[2] if len(sys.argv) >= 3 else None )

else:
    usage.show_usage()

## Errors
if err is not None:
    print(err)
    print()
    usage.show_usage()