#!/usr/bin/python3

from nitwit.actions import commit_message
from nitwit.helpers.settings import load_settings

import sys, os

if (settings := load_settings()) is None:
    print("Couldn't load git config")
    exit(1)

if len(sys.argv) <= 1:
    print("Didn't get the message file")
    exit(1)

# Update the message
print(sys.argv[1])
commit_message.handle_prepare_commit( settings, sys.argv[1] )
exit(0)